language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install
script:
  - npm run -s build
  - npm run -s build-examples
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
